### ISSUE TITLE
Possible duplicates in correction list

### ISSUE THREAD

**Issue by adam-ra** [dominedo/spark-n-spell#1]
I've noticed something which is most likely a bug in dictionary building code of symspell_python. My impression is that it should be “if *w* not in dictionary[item][0]”

    # add (correct) word to delete's suggested correction list 
    # if not already there
    if item not in dictionary[item][0]:
        dictionary[item][0].append(w)

This is here: https://github.com/dominedo/spark-n-spell/blob/master/symspell_python.py#L136

**Comment by ppgmg** [comment]
Hi Adam:  Thanks for your comment. I think you are right in that "if item" should be "if w" to match the preceding comment. You prompted me to take another look at the correction lists though and, interestingly, noticed that none of them had duplicates. It turns out the condition is **always** satisfied (whether _w_ or _item_ is referenced) since the code is within a block that is only executed upon the first addition of a new dictionary item _w_, and so _w_ would never have been in the list to begin with anyway.

I believe the original Symspell code had a similar condition, but in view of the above I think "if w not in dictionary[item][0]:" can in fact be left out all together. Note that we tried to generally mirror the original code for this port, so there may also be other optimizations that can be made.  

Cheers, Ken
